<a href="https://colab.research.google.com/github/Sheilascientist/Finan-as/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np #Importa o pacote numpy.

In [ ]:
a = np.array([0, 0.5, 1., 1.5, 2.0 ])
a #Cria um objeto ndarray a partir de um objeto de lista com floats.

In [7]:
type(a) #Cria um objeto ndarray a partir de um objeto de lista com floats.

numpy.ndarray

In [ ]:
a = np.array(['a','b','c'])
a  #Cria um objeto ndarray a partir de um objeto de lista com strs.

In [9]:
a = np.arange(2, 20, 2)
a #np.arange() funciona de forma semelhante a range() …

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
a = np.arange(8, dtype=np.float)
a  #… mas recebe como entrada adicional o parâmetro dtype.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([0., 1., 2., 3., 4., 5., 6., 7.])

In [11]:
a[5:] #Com objetos array unidimensionais, a indexação funciona normalmente

array([5., 6., 7.])

In [12]:
a[:2] #Com objetos array unidimensionais, a indexação funciona normalmente

array([0., 1.])

In [13]:
a.sum() #A soma de todos os elementos.

28.0

In [14]:
a.std() #O desvio padrão dos elementos

2.29128784747792

In [15]:
a.cumsum() #A soma cumulativa de todos os elementos (começando na posição do índice 0)

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

# Outra característica importante são as operações matemáticas (vetorizadas) definidas em objetos de matriz:

In [16]:
l = [0. , 0.5, 1.5, 3., 5.]
2*l #A multiplicação escalar com objetos de lista leva a uma repetição de elementos.

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

In [17]:
a

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [18]:
2*a #Por outro lado, trabalhar com objetos de matriz implementa uma multiplicação escalar adequada

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [19]:
a**2 #Isso calcula os valores quadrados por elemento.

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [20]:
2**a #Isso interpreta os elementos do ndarray como os poderes.

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [21]:
a**a #Isso calcula o poder de cada elemento para si mesmo.

array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

Funções universais são outro recurso importante do pacote NumPy. Eles são “universais” no sentido de que, em geral, operam em objetos ndarray, bem como em tipos de dados básicos do Python. No entanto, ao aplicar funções universais a, digamos, um
Objeto flutuante Python, é preciso estar atento ao desempenho reduzido em comparação com a mesma funcionalidade encontrada no módulo math:

In [22]:
np.exp(a) #Calcula os valores exponenciais elemento a elemento.

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [23]:
np.sqrt(a) #Calcula a raiz quadrada para cada elemento.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [24]:
np.sqrt(2.5) #Calcula a raiz quadrada para um objeto float Python.

1.5811388300841898

In [25]:
import math #O mesmo cálculo, desta vez usando o módulo de matemática.

In [26]:
math.sqrt(2.5) #A função math.sqrt() não pode ser aplicada diretamente ao objeto ndarray.

1.5811388300841898

In [27]:
math.sqrt(a) #A função math.sqrt() não pode ser aplicada diretamente ao objeto ndarray.

TypeError: ignored

In [28]:
%timeit np.sqrt(2.5) #Aplicando a função universal np.sqrt() a um objeto float Python…

The slowest run took 44.87 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 806 ns per loop


In [29]:
%timeit math.sqrt(2.5) #… é muito mais lento que a mesma operação com a função math.sqrt().

The slowest run took 22.73 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 5: 98.7 ns per loop


# Múltiplas Dimensões

In [31]:
b = np.array([a, a * 2])
b   #Constrói um objeto ndarray bidimensional a partir do unidimensional.

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [32]:
b[0]  #Seleciona a primeira linha.

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [33]:
b[0, 2]   #Seleciona o terceiro elemento na primeira linha; índices são separados, dentro dos colchetes

2.0

In [35]:
b[:, 1]  #Seleciona a segunda coluna.

array([1., 2.])

In [36]:
b.sum() #Calcula a soma de todos os valores

84.0

In [37]:
b.sum(axis=0)   #Calcula a soma ao longo do primeiro eixo; ou seja, em coluna.

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [38]:
b.sum(axis=1)  #Calcula a soma ao longo do segundo eixo; ou seja, em linha

array([28., 56.])

In [42]:
c = np.zeros((2, 3), dtype='i', order='C')
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [47]:
c = np.ones((2, 3, 4), dtype='i', order='C')
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [49]:
d = np.zeros_like(c, dtype='f16', order='C')
d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]], dtype=float128)

In [50]:
d = np.ones_like(c, dtype='f16', order='C')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float128)

In [51]:
e = np.empty((2, 3, 2))
e

array([[[2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314]],

       [[2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314],
        [2.12199579e-314, 2.12199579e-314]]])

In [52]:
f = np.empty_like(c)
f

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int32)

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
g = np.linspace(5, 15, 12)
g

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

# Metainformação  

Cada objeto ndarray fornece acesso a vários atributos úteis

In [59]:
g.size  #O número de elementos

12

In [60]:
g.itemsize   #O número de bytes usados para representar um elemento.

8

In [61]:
g.ndim  #O número de dimensões.

1

In [62]:
g.shape  #A forma do objeto ndarray.

(12,)

In [63]:
g.dtype  #O dtype dos elementos.

dtype('float64')

In [64]:
g.nbytes  #O número total de bytes usados na memória.

96

# Remodelação e redimensionamento

In [66]:
g = np.arange(15)
g

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
g.shape

(15,)

In [68]:
np.shape(g)

(15,)

In [69]:
g.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
h = g.reshape((5, 3))
h

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [73]:
h.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [75]:
h.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])